# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.box = "learningchef/centos65"

  config.vm.provision "file", 
     source: "/Volumes/Macintosh HD 3/vagrant_demo/vagrant_chef_demo/vagrant/files/git-config", 
     destination: "~/.gitconfig"

  config.vm.provision "shell",
     path: "https://raw.githubusercontent.com/Nishanthk3/vagrant_chef_demo/master/vagrant/scripts/centos-common.sh"

  config.omnibus.chef_version = :latest

  config.vm.network "forwarded_port", guest: 8080, host:8080

  config.vbguest.auto_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = ["/Volumes/Macintosh HD 3/vagrant_demo/vagrant_chef_demo/vagrant/chef/supermarket", "/Volumes/Macintosh HD 3/vagrant_demo/vagrant_chef_demo/vagrant/chef/cookbooks"]
  # chef.roles_path = "../my-recipes/roles"
    chef.add_recipe "java"
    chef.add_recipe "vagrant_tomcat"
  # chef.add_role "web"
    chef.json = { 
            "java" => {
                "jdk_version" => "7"
              }
            }
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL
end
